### ISSUE TITLE
Restricted font

### ISSUE THREAD

**Issue by kakasuarez** [suryashekharc/insta_reddit#2]
The given link for installing fonts (https://www.cufonfonts.com/font/helvetica-neue-9) states:
> This font has been restricted by Cufon Fonts for copyright reasons.

Maybe remove the link in the README and comments and ask the user to install a font of their own choice and make appropriate changes to the code?

**Comment by suryashekharc** [comment]
Hey thanks for calling this out. I switched to plainvanilla Arial. I contemplated doing that but felt like it could compromise usability. Advanced users can simply search for the use of arial.ttf and be able to replace them appropriately.
